# Generated by Django 5.0.6 on 2024-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='preference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
